# permissions for end users to edit sums.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: sum-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: k8s-abc
    app.kubernetes.io/part-of: k8s-abc
    app.kubernetes.io/managed-by: kustomize
  name: sum-editor-role
rules:
- apiGroups:
  - calc.trod.k8s.io
  resources:
  - sums
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - calc.trod.k8s.io
  resources:
  - sums/status
  verbs:
  - get
