apiVersion: calc.trod.k8s.io/v1
kind: Sum
metadata:
  labels:
    app.kubernetes.io/name: sum
    app.kubernetes.io/instance: sum-sample
    app.kubernetes.io/part-of: k8s-abc
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: k8s-abc
  name: sum-sample
spec:
  # TODO(user): Add fields here
